### ISSUE TITLE
Password Protect FreeFileSync - No VNC 

### ISSUE THREAD

**Issue by kenrmayfield** [jlesage/docker-freefilesync#10]
### Idea

@jlesage 

I noticed there was a Password Protect Setup for VNC.  However I am not using VNC.

Is there a way to Setup Password Protect FreeFileSynce if you are not using VNC?

**Comment by jlesage** [comment]
When you set a password via `VNC_PASSWORD`, it applies to both the web interface and VNC clients.

**Comment by kenrmayfield** [comment]
@jlesage 

Thanks for the Quick Response.

Closing Ticket
