### ISSUE TITLE
FreeFileSync Docker Pull in a Privileged LXC Container Error - docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "c 10:200 rwm": write /sys/fs/cgroup/devices/docker/89b35b9dbd465c3864c9a969044284dd9d4b101d51e21d5cb2f52e0849330e98/devices.allow: operation not permitted: unknown.

### ISSUE THREAD

**Issue by kenrmayfield** [jlesage/docker-freefilesync#11]
### Current Behavior

@jlesage 

When running a Docker Pull FreeFileSync in a Privileged LXC Container,  Docker Pull Errors:
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "c 10:200 rwm": write /sys/fs/cgroup/devices/docker/89b35b9dbd465c3864c9a969044284dd9d4b101d51e21d5cb2f52e0849330e98/devices.allow: operation not permitted: unknown.

**I found the File that needs to be Edited to Add c 10:200 rwm however it is Read Only:**
[root@FreeFileCentOS8 docker]# cat /sys/fs/cgroup/devices/devices.list
c *:* m
b *:* m
c 1:3 rwm
c 1:5 rwm
c 1:7 rwm
c 5:0 rwm
c 5:1 rwm
c 5:2 rwm
c 1:8 rwm
c 1:9 rwm
c 136:* rwm
c 10:229 rwm
[root@FreeFileCentOS8 docker]# ls -l /sys/fs/cgroup/devices/devices.list
-r--r--r-- 1 root root 0 Sep  5 02:12 /sys/fs/cgroup/devices/devices.list

**Does this Relate to Adding the TunTap Device to the Docker Profile?**
docker tuntap unix-char path=/dev/net/tun
or 
[Container Name] tuntap unix-char path=/dev/net/tun

If I use a UnPrivileged LXC Container,  Docker Pull Installs FreeFileSync with no problems.

I am using Proxmox with **LXC Container CentOS Stream 8**.   I do have Nested Turned On in Options for Privileged.  If 
UnPrivileged, I have Nested and KeyCTL Turned On.

In Proxmox under Resources I have created Two Mount Points to use as Storage Backup Drives.  I am trying to Access the Mount Point Storage Backup Drives using FreeFileSync........that is the reason for the Privileged Container.   
If I use a UnPrivileged LXC Container then I only have Access to Mount Points within FreeFileSync's File System.

In order to Access Shares for FreeFileSync to Backup, I do know I will have to Install the SAMBA-Client on the **LXC Container CentOS Stream 8** and then Mount the Share Points within the **LXC Container CentOS Stream 8** so that FreeFileSync can have Access to the Shares.  **Can this be done within FreeFileSync's by Accessing FreeFileSync's Terminal?**  **Can the SAMBA-Client be Installed within FreeFileSynce?**

### Expected Behavior

1.  Install FreeFileSync in Privileged LXC Container
3.  Use Mount Points Setup in Proxmox under Resources
4.  Backup CIF or NFS Shares

### Container creation

The Docker Pull Command below used for Both Privileged and UnPrivileged LXC Containers:

docker pull jlesage/freefilesync

### Container log

```text
89b35b9dbd465c3864c9a969044284dd9d4b101d51e21d5cb2f52e0849330e98
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "c 10:200 rwm": write /sys/fs/cgroup/devices/docker/89b35b9dbd465c3864c9a969044284dd9d4b101d51e21d5cb2f52e0849330e98/devices.allow: operation not permitted: unknown.
```

**Comment by kenrmayfield** [comment]
@jlesage 

Hey I was checking back on my Previous Message?

**Comment by jlesage** [comment]
Sorry for the delayed answer.  I don't have a lot of experience with Proxmox or docker in LXC containers.  From what I understand, this is not an issue specific to FreeFileSync container and any container would have the same problem.

Did you also seek help from the Proxmox forum ?

**Comment by jlesage** [comment]
Closing this issue. Please re-open if needed.
