### ISSUE TITLE
Unable to access WebUI

### ISSUE THREAD

**Issue by chop249** [jlesage/docker-freefilesync#13]
### Current Behavior

I am trying to access the WebUI via http://XXX.XXX.XXX.XXX:5800 and cannot. I tried both Docker Run and Docker Compose. 

### Expected Behavior

Access WebUI via http://XXX.XXX.XXX.XXX:5800

### Environment

- OS:Debian Container
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

docker run -d \
    --name=freefilesync \
    -p 5800:5800 \
    -v /docker/appdata/freefilesync:/config:rw \
    -v /home/user:/storage:rw \
    jlesage/freefilesync

### Container log

```text
.
```

**Comment by jlesage** [comment]
Is the container able to start, without port conflict ?

Please provide the container log by running the following command:
```
docker logs freefilesync
```

**Comment by chop249** [comment]
That provides:
root@FreeFileSync:~# docker logs freefilesync
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
[cont-env    ] APP_VERSION: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK2_RC_FILES: executing...
[cont-env    ] GTK2_RC_FILES: terminated successfully.
[cont-env    ] GTK2_RC_FILES: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] XDG_STATE_HOME: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: sed: can't move '/etc/group' to '/etc/group.bak': Invalid argument
[cont-init   ] 10-init-users.sh: terminated with error 1.

**Comment by jlesage** [comment]
Ok, the container fails to start.
Are you using Docker on a zfs storage ?

**Comment by chop249** [comment]
Yes, Proxmox container on ZFS.

**Comment by jlesage** [comment]
This issue happens because overlay2 on zfs doesn't support `RENAME_WHITEOUT` operation.
See https://github.com/jlesage/docker-jdownloader-2/issues/137 for workarounds and solutions.

**Comment by chop249** [comment]
Followed this and it somehow removed the freefilesync container. 

[guba91](https://github.com/guba91) commented [on Feb 7](https://github.com/jlesage/docker-freefilesync/issues/13#issuecomment-1420894072)
for me this procedure worked and i'm able to replicate it:
enable keyctl, nesting, fuse on lxc container, then reboot lxc.
mkdir /etc/docker
nano /etc/docker/daemon.json
{
  "storage-driver": "fuse-overlayfs"
} <- put this inside the new file daemon.json
apt install fuse-overlayfs
fuse-overlayfs --version
reboot lxc or reload docker service
docker info if you see Storage Driver: fuse-overlayfs is done..

If I try to rerun the docker run it now fails.

**Comment by jlesage** [comment]
> If I try to rerun the docker run it now fails.

What is the error ?

**Comment by chop249** [comment]
docker: failed to register layer: Error processing tar file(using mount program fuse-overlayfs: fuse: device not found, try 'modprobe fuse' first
fuse-overlayfs: cannot mount: No such file or directory
: exit status 1): .
See 'docker run --help'.


But running docker info I see Storage Driver: fuse-overlayfs.

**Comment by jlesage** [comment]
Did you try to load the driver with `modprobe fuse` ?

**Comment by chop249** [comment]
Yes. I edited the last post earlier. That output is at the bottom but here it is again. 
`root@FreeFileSync:# modprobe fuse
modprobe: FATAL: Module fuse not found in directory /lib/modules/5.15.102-1-pve
root@FreeFileSync:# fuse-overlayfs --version
fuse-overlayfs: version 1.4
FUSE library version 3.10.3
using FUSE kernel interface version 7.31
fusermount3 version: 3.10.3`

**Comment by jlesage** [comment]
> modprobe fuse modprobe: FATAL: Module fuse not found in directory /lib/modules/5.15.102-1-pve

Maybe you have the install a package that provide the driver ?  Sorry, I don't have experience with Proxmox.  Maybe you should also seek help on the Proxmox's forum.  I'm sure this issue was already discussed.

**Comment by chop249** [comment]
@jlesage I threw in the towel and moved that CT to an LVM-Thin drive. 🤣 Worked right away. Thanks for trying to help! I appreciate it.

**Comment by jlesage** [comment]
I'm glad to see that it's now working for you.
Thanks for the update !
