### ISSUE TITLE
The language cannot be displayed as Chinese

### ISSUE THREAD

**Issue by kokojacket** [jlesage/docker-freefilesync#6]
### Current Behavior

I noticed that when I changed to Chinese display, the interface became garbled

### Environment

- OS:openwrt
- OS version:5.4.188
- CPU:Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz
- Docker version:
- Device model:
- Browser/OS:

### Container creation

version: '3'

services:
  freefilesync:
    image: jlesage/freefilesync
    container_name: FreeFileSync
    ports:
      - "5800:5800"
    volumes:
      - "/mnt/130G/ddocker/FreeFileSync:/config:rw"
      - "/Synctest:/storage:rw"
    environment:
      - LANG=zh_CN
      - PUID=0   
      - PGID=0    
      - UMASK=000 

### Container log

```text
none
```

**Comment by jlesage** [comment]
Try to set the `ENABLE_CJK_FONT` environment variable to `1`.
https://github.com/jlesage/docker-freefilesync#environment-variables

**Comment by jlesage** [comment]
Great!
