### ISSUE TITLE
[Bug] Container crash on start

### ISSUE THREAD

**Issue by update-freak** [jlesage/docker-freefilesync#8]
### Current Behavior

I want to set up a docker container with on my Synology NAS as docker.
I already installed also FileBot and JDownloader 2 from your repo with equal docker compose.
When the container is startet it got crashed. I dont know why. I created a folder in \volume1\docker\freefilesync.

### Expected Behavior

No error when I start the container

### Steps To Reproduce

see above

### Environment

- NAS: DS 716+
- Docker version: current App of Synology

### Container creation

docker run -d --name=FreeFileSync \
-p 5804:5800 \
-e USER_ID=1026 \
-e GROUP_ID=100 \
-e LANG=de_DE.UTF-8 \
-e TZ=Europe/Berlin \
-v /volume1/docker/freefilesync:/config:rw \
-v /volume1:/storage:rw \
jlesage/freefilesync

### Container log

```text
[supervisor  ] loading service 'crond'...
[supervisor  ] service 'crond' is disabled.
[supervisor  ] all services loaded.
[supervisor  ] starting services...
[supervisor  ] starting service 'xvnc'...
[xvnc        ] Xvnc TigerVNC 1.13.1 - built May 16 2023 18:07:02
[xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc        ] Underlying X server release 12014000
[xvnc        ] Thu Aug 17 21:26:19 2023
[xvnc        ]  vncext:      VNC extension running!
[xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc        ]  vncext:      created VNC server for screen 0
[supervisor  ] starting service 'nginx'...
[nginx       ] Listening for HTTP connections on port 5800.
[supervisor  ] starting service 'openbox'...
[supervisor  ] starting service 'app'...
[supervisor  ] all services started.
[app         ] terminate called after throwing an instance of 'std::runtime_error'
[app         ]   what():  ../../zen/guid.h[31] Failed to generate GUID.
[app         ] ENOSYS: Function not implemented [getentropy]
[supervisor  ] service 'app' exited (got signal SIGABRT).
[supervisor  ] service 'app' exited, shutting down...
[supervisor  ] stopping service 'openbox'...
[supervisor  ] service 'openbox' exited (with status 0).
[supervisor  ] stopping service 'nginx'...
[supervisor  ] service 'nginx' exited (with status 0).
[supervisor  ] stopping service 'xvnc'...
[xvnc        ] Thu Aug 17 21:26:24 2023
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[supervisor  ] service 'xvnc' exited (with status 0).
[finish      ] executing container finish scripts...
[finish      ] all container finish scripts executed.
```

**Comment by jlesage** [comment]
What kernel version the NAS is running (`uname -a`) ?

Do you see the same crash if you run:
```
docker run --rm --privileged jlesage/freefilesync
```

**Comment by update-freak** [comment]
With the command I got
`Linux NAS 3.10.108 #64570`

I also asked here: https://www.kodinerds.net/thread/77519-freefilesync-docker-container/

**Comment by jlesage** [comment]
Is your Synology up-to-date ?  This is a very nice old kernel.

According to https://www.gnu.org/software/libc/manual/html_node/Unpredictable-Bytes.html, support for `getentropy` has been added to kernel 3.17.  That explains the error raised by FreeFileSync.

**Comment by update-freak** [comment]
Yes, my Synology NAS (DS 716+) is up to date. Hope that Synology will bring a kernel update in future.

Ok, thanks for explanation. This causes the error

**Comment by jlesage** [comment]
So you are running DSM 7.2 ?

**Comment by update-freak** [comment]
Yes, I'm on DSM 7.2

**Comment by jlesage** [comment]
Can you try the latest version ?  I removed usage of `getentropy()`.

**Comment by update-freak** [comment]
Thank you very much for the update.
Now it works.
